const SUPABASE_URL='https://thwxctipszzdvxjpegdm.supabase.co';const SUPABASE_KEY='sb_publishable_3W1TRYwdtncqHEBe8BjIUw_9sYl2Cce';const sb=(await import('https://esm.sh/@supabase/supabase-js@2')).createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);const login=$('#login'),panel=$('#panel'),msg=$('#loginMsg');
async function load(){const {data:{session}}=await sb.auth.getSession();if(session){const {data:admin}=await sb.from('admin_users').select('email').ilike('email',session.user.email).maybeSingle();if(admin){login.classList.add('hidden');panel.classList.remove('hidden');await refresh()}else{await sb.auth.signOut();msg.textContent='Esta cuenta no tiene acceso al panel.'}}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();msg.textContent='Ingresando…';const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)msg.textContent=error.message;else await load()});
$('#logout').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
async function refresh(){const {data}=await sb.from('cam_gallery').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});$('#adminGallery').innerHTML=(data||[]).map(x=>`<div class="admin-item" data-id="${x.id}"><img src="${x.image_url}" alt=""><button class="delete" title="Eliminar">×</button></div>`).join('')||'<p class="muted">Todavía no hay fotos.</p>';document.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{const id=b.parentElement.dataset.id;const item=data.find(x=>x.id===id);if(!confirm('¿Eliminar esta foto?'))return;await sb.storage.from('cam-gallery').remove([item.storage_path]);await sb.from('cam_gallery').delete().eq('id',id);await refresh()});const {data:s}=await sb.from('cam_site_settings').select('*').eq('id',1).single();if(s){$('#instagram').value=s.instagram_url;$('#phone').value=s.phone;$('#location').value=s.location}}
$('#files').addEventListener('change',async e=>{const files=[...e.target.files];for(const file of files){const ext=file.name.split('.').pop().toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const up=await sb.storage.from('cam-gallery').upload(path,file,{cacheControl:'31536000',upsert:false});if(up.error){alert(up.error.message);continue}const {data:url}=sb.storage.from('cam-gallery').getPublicUrl(path);const {count}=await sb.from('cam_gallery').select('*',{count:'exact',head:true});await sb.from('cam_gallery').insert({image_url:url.publicUrl,storage_path:path,sort_order:(count||0)+1})}e.target.value='';await refresh()});
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.from('cam_site_settings').update({instagram_url:$('#instagram').value,phone:$('#phone').value,location:$('#location').value,updated_at:new Date().toISOString()}).eq('id',1);$('#settingsMsg').textContent=error?error.message:'Cambios guardados.'});
await load();
