const SUPABASE_URL='https://thwxctipszzdvxjpegdm.supabase.co';const SUPABASE_KEY='sb_publishable_3W1TRYwdtncqHEBe8BjIUw_9sYl2Cce';const sb=(await import('https://esm.sh/@supabase/supabase-js@2')).createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s),login=$('#login'),panel=$('#panel'),msg=$('#loginMsg');
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function isAdmin(){const {data:{session}}=await sb.auth.getSession();if(!session)return false;const {data:admin}=await sb.from('admin_users').select('email').ilike('email',session.user.email).maybeSingle();return !!admin}
async function load(){if(await isAdmin()){login.classList.add('hidden');panel.classList.remove('hidden');await refresh()}else{await sb.auth.signOut();}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();msg.textContent='Ingresando…';const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)msg.textContent='No pudimos iniciar sesión. Revisá tu email y contraseña.';else await load()});
$('#logout').addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});
async function uploadImage(file,path){const up=await sb.storage.from('cam-gallery').upload(path,file,{cacheControl:'31536000',upsert:true,contentType:file.type});if(up.error)throw up.error;return sb.storage.from('cam-gallery').getPublicUrl(path).data.publicUrl}
async function refresh(){
 const {data}=await sb.from('cam_gallery').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});
 $('#adminGallery').innerHTML=(data||[]).map(x=>`<div class="admin-item" data-id="${x.id}"><img src="${esc(x.image_url)}" alt=""><button class="delete" title="Eliminar">×</button></div>`).join('')||'<p class="muted">Todavía no hay fotos.</p>';
 document.querySelectorAll('.admin-grid .delete').forEach(b=>b.onclick=async()=>{const id=b.parentElement.dataset.id,item=data.find(x=>x.id===id);if(!confirm('¿Eliminar esta foto?'))return;await sb.storage.from('cam-gallery').remove([item.storage_path]);await sb.from('cam_gallery').delete().eq('id',id);await refresh()});
 const {data:s}=await sb.from('cam_site_settings').select('*').eq('id',1).single();if(s){$('#instagram').value=s.instagram_url||'';$('#phone').value=s.phone||'';$('#location').value=s.location||''}
 const {data:services}=await sb.from('cam_services').select('*').order('sort_order',{ascending:true});
 $('#servicesAdmin').innerHTML=(services||[]).map(x=>`<article class="service-admin-card" data-id="${esc(x.id)}"><div class="service-admin-image">${x.image_url?`<img src="${esc(x.image_url)}" alt="${esc(x.name)}">`:'<span>＋</span>'}</div><div><p class="eyebrow">SERVICIO</p><h3>${esc(x.name)}</h3><p class="muted">${esc(x.description||'')}</p><label class="mini-upload"><input class="service-file" type="file" accept="image/*">${x.image_url?'Cambiar foto':'Subir foto'}</label>${x.image_url?'<button class="text-delete service-delete" type="button">Eliminar foto</button>':''}<p class="form-msg service-msg"></p></div></article>`).join('');
 document.querySelectorAll('.service-file').forEach(input=>input.onchange=async()=>{const card=input.closest('.service-admin-card'),id=card.dataset.id,file=input.files[0];if(!file)return;const service=services.find(x=>x.id===id);const msg=card.querySelector('.service-msg');msg.textContent='Subiendo…';try{if(service.storage_path)await sb.storage.from('cam-gallery').remove([service.storage_path]);const path=`services/${id}.${file.name.split('.').pop().toLowerCase()}`;const url=await uploadImage(file,path);const {error}=await sb.from('cam_services').update({image_url:url,storage_path:path,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;await refresh()}catch(e){msg.textContent=e.message||'No se pudo subir la foto.'}});
 document.querySelectorAll('.service-delete').forEach(b=>b.onclick=async()=>{const card=b.closest('.service-admin-card'),id=card.dataset.id,service=services.find(x=>x.id===id);if(!confirm('¿Eliminar la foto de este servicio?'))return;if(service.storage_path)await sb.storage.from('cam-gallery').remove([service.storage_path]);await sb.from('cam_services').update({image_url:null,storage_path:null,updated_at:new Date().toISOString()}).eq('id',id);await refresh()});
}
$('#files').addEventListener('change',async e=>{const files=[...e.target.files];for(const file of files){try{const ext=file.name.split('.').pop().toLowerCase(),path=`gallery/${crypto.randomUUID()}.${ext}`,url=await uploadImage(file,path);const {count}=await sb.from('cam_gallery').select('*',{count:'exact',head:true});const {error}=await sb.from('cam_gallery').insert({image_url:url,storage_path:path,sort_order:(count||0)+1,alt_text:'Trabajo de uñas de lasuniasdecam'});if(error)throw error}catch(err){alert(err.message||'No se pudo subir una foto.')}}e.target.value='';await refresh()});
$('#settingsForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.from('cam_site_settings').update({instagram_url:$('#instagram').value.trim(),phone:$('#phone').value.trim(),location:$('#location').value.trim(),updated_at:new Date().toISOString()}).eq('id',1);$('#settingsMsg').textContent=error?error.message:'Cambios guardados.'});
await load();
